# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define :servidorFirewall do |servidorFirewall|
    servidorFirewall.vm.box = "bento/ubuntu-22.04"
    servidorFirewall.vm.network :private_network, ip: "192.168.50.3"
    servidorFirewall.vm.hostname = "UFW"

    config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get upgrade -y
      apt-get install bind9 net-tools dnsutils -y
    SHELL
    
  end
  
  config.vm.define :servidorSFTP do |servidor|
    servidor.vm.box = "bento/ubuntu-22.04"
    servidor.vm.network :private_network, ip: "192.168.50.2"
    servidor.vm.hostname = "SFTP"

    config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get upgrade -y
      apt-get install net-tools dnsutils apache2 vsftp -y
    SHELL
    
  end
end