# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define :servidorDoT do |servidorDoT|
    servidorDoT.vm.box = "bento/ubuntu-22.04"
    servidorDoT.vm.network :private_network, ip: "192.168.50.11"
    servidorDoT.vm.hostname = "servidorDNSoverTLS"

    config.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get upgrade -y
      apt-get install bind9 net-tools dnsutils -y
    SHELL
    
  end 

end